version: '3.8'

services:
  django:
    container_name: django
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8001:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-4v*ex1+wyquxn_f1#o)6%lmk5u-zqkpbp=h2=haz^@r=9j6_&$
      - ALLOWED_HOSTS=localhost,127.0.0.1
